intent_classification:
  model: gemini
  params:
    model_name: gemini-1.0-pro
    configuration:
      temperature: 0

model_garden:
  gemini:
    name: Gemini
    path: chatbot.dependencies.language_models.Gemini