intent_classifier:
  model: gemini
  model_settings:
    temperature: 0

document_embedder:
  embedding_model: openaiembeddings
  text_splitter:
    type: RecursiveCharacterTextSplitter
    params:
      chunk_size: 100
      chunk_overlap: 0

information_retriever:
  embedding_model: openaiembeddings

response_generator:
  generator_model: gemini
  model_settings:
    temperature: 0

title_generator:
  model: gemini

model_garden:
  gemini:
    name: Gemini
    path: chatbot.dependencies.language_models.Gemini
    params:
      model_name: gemini-1.0-pro
  openaiembeddings:
    name: OpenAIEmbeddings
    path: chatbot.dependencies.language_models.OpenAIEmbeddings
    params:
      model_name: text-embedding-3-large

prompts:
  directory: prompts/