intent_classifier:
  model: gemini
  model_settings:
    temperature: 0

model_garden:
  gemini:
    name: Gemini
    path: chatbot.dependencies.language_models.Gemini
    params:
      model_name: gemini-1.0-pro

prompts:
  directory: prompts/