intent_classification:
  model: gemini

model_garden:
  - gemini:
      model_path: chatbot.dependencies.language_models.Gemini
  - openaiembedding:
      model_path: chatbot.dependencies.language_models.OpenAIEmbedding