intent_classifier:
  model: gemini
  model_settings:
    temperature: 0

document_embedder:
  embedding_model: openaiembeddings
  text_splitter:
    type: RecursiveCharacterTextSplitter
    params:
      chunk_size: 600
      chunk_overlap: 120

information_retriever:
  embedding_model: openaiembeddings
  retriever_settings:
    k: 10

response_generator:
  generator_model: gemini
  model_settings:
    temperature: 1
    top_p: 0.95

title_generator:
  model: gemini

model_garden:
  gemini:
    name: Gemini
    path: chatbot.dependencies.language_models.Gemini
    params:
      model_name: gemini-1.5-flash
  openaiembeddings:
    name: OpenAIEmbeddings
    path: chatbot.dependencies.language_models.OpenAIEmbeddings
    params:
      model_name: text-embedding-3-large

prompts:
  directory: prompts/