"""adding question answer

Revision ID: 08d9bf3b18eb
Revises: cf36f38837be
Create Date: 2024-08-14 14:22:12.553625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08d9bf3b18eb'
down_revision: Union[str, None] = 'cf36f38837be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=255), nullable=False),
    sa.Column('staff_answer', sa.String(length=255), nullable=True),
    sa.Column('bot_answer', sa.String(length=255), nullable=True),
    sa.Column('intent', sa.String(length=255), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('questioner_email', sa.String(length=255), nullable=True),
    sa.Column('questioner_name', sa.String(length=255), nullable=True),
    sa.Column('answered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('messages', 'text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294000000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'text',
               existing_type=sa.Text(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.drop_table('questions')
    # ### end Alembic commands ###
