"""add usertype in conversation

Revision ID: 6a1b3248e103
Revises: f7fc7e5ed5e1
Create Date: 2024-07-15 23:48:14.910567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1b3248e103'
down_revision: Union[str, None] = 'f7fc7e5ed5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user_type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'user_type')
    # ### end Alembic commands ###
