"""add access_level in User

Revision ID: 83715f75ba31
Revises: eb1850e8b6dd
Create Date: 2024-07-15 19:39:47.044316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83715f75ba31'
down_revision: Union[str, None] = 'eb1850e8b6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_level')
    # ### end Alembic commands ###
