"""add name column to conversation

Revision ID: eb1850e8b6dd
Revises: cbd9f2fcd7a2
Create Date: 2024-07-15 13:59:05.376079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1850e8b6dd'
down_revision: Union[str, None] = 'cbd9f2fcd7a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'name')
    # ### end Alembic commands ###
