name: CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10.14]

    services:
      # Define MySQL service with a specific version
      mysql:
        image: mysql:8.0  # Adjust version if needed

    env:
      # Store database credentials securely using GitHub Secrets
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -

    - name: Install dependencies
      run: |
        poetry install

    - name: Install MySQL client (for Ubuntu only)
      # Assuming Ubuntu runner for MySQL client installation
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Apply Alembic migrations
      run: |
        poetry run alembic upgrade head

    - name: Run tests
      run: |
        poetry run pytest -m "not integration"
